name: lallanai_test

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Use a stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Create a zip file
        run: zip -r app.zip . -x "node_modules/*"  # Exclude node_modules

      - name: List files and current directory
        run: |
          ls -lah
          pwd

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/lallan-ai_testing
            unzip -o app.zip
            rm -f app.zip
            source ~/.nvm/nvm.sh
            nvm use 18  # Use the same Node.js version as in the workflow
            npm install  # If needed
            echo "--------------Before Restart-----------------"
            pm2 list
            pm2 restart 0
            echo "--------------After Restart------------------"
            pm2 list
